### ISSUE TITLE
Non-promises-based Examples?

### ISSUE THREAD

**Issue by ohenepee** [AppSecurityApi/com-intel-security-cordova-plugin#1]
How do non-ES6 devs implement the API? I can't find any callback-based examples.

**Comment by ohenepee** [comment]
Is there a way to convert the promises-based examples to callbacks-based?

**Comment by DanShmulIntel** [comment]
Hi,
The callback based API of App Security API plugin is deprecated.
However, you can still use the callback format (again, not recommended) by going over these samples:

  *   https://software.intel.com/en-us/xdk/article/my-private-notes-sample  which demonstrates secureData & secureStorage
  *   https://software.intel.com/en-us/xdk/article/my-private-photos-sample which demonstrates secureData, secureStorage & secureTransport.

If you have some questions on how to use the supported promises of the API, do not hesitate to contact us for assistance.
Thanks,
Dan.

**Comment by ohenepee** [comment]
Thanks.. will do!
