### ISSUE TITLE
Use in Ionic / Angular?

### ISSUE THREAD

**Issue by TrueGeek** [AppSecurityApi/com-intel-security-cordova-plugin#10]
I'm trying to use this plugin in Ionic. I have this controller:

`app.controller('TestController', ($scope) => {

    $scope.secureDataRead = function() {

        intel.security.secureStorage.read({ 'id': 'test.1' })

            .then(function (instanceID) {
                    console.log('success: instanceID = ' + instanceID);
                })

            .catch(function (errorObj) {
                console.log('fail: code = ' + errorObj.code + ', message = ' + errorObj.message);
            });
    };

});`

But "intel" in "intel.security..." is undefined:

`"TypeError: Cannot read property 'security' of undefined`

Is there a service name I should put in the constructor, and if so, what is that service name?

Thanks!

**Comment by DanShmulIntel** [comment]
Hi TrueGeek,

What is the platform which you are running on? Android/iOS/Windows Modern UI?

Angular controllers are out of scope for this plugin version. but what you can try is register to 'deviceready' event and then call intel.security.secureStorage.read(...).

something like:

document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
    // Now safe to use Cordova APIs (App Security API plugin)
   intel.security.secureStorage.read(...);
}

Thanks,
Dan.

**Comment by TrueGeek** [comment]
We're targeting Android and iOS. I tried the code above but it still complains about "intel" not being defined.

Thanks for your quick response, but it looks like without Angular support this won't work.
