### ISSUE TITLE
Fail to deploy cordova project in VS 2017 because of "could not locate the appxrecipe file"

### ISSUE THREAD

**Issue by mbraude** [AppSecurityApi/com-intel-security-cordova-plugin#13]
If you add this plugin to a Cordova project in VS 2017, the project will no longer deploy to the Windows platform. The reason is because the plugin changes the output path from build\windows to build\windows8.1 and build\windows10. This causes VS deployment to fail, and later on users see this cryptic error message:

 Error: DEP01700 : Could not locate the appxrecipe file. You may need to build your project.

Steps to reproduce:

1) Install VS 2017 RC from https://www.visualstudio.com/vs/visual-studio-2017-rc/
2) Add the Cordova workload and include the Windows Build Tools as an optional dependency.
3) Create a new Cordova project and add the intel security plugin.
4) Build and deploy for Windows-x86

Expected: build succeeds.
Actual: build fails with DEP01700. The reason is because VS expects the files to be in build\windows, but instead they are in build\windows10. Here is a sample build log:

Message in Output windows is as below:
1>------ Build started: Project: BlankCordovaApp4, Configuration: Debug Windows-x86 ------
Cordova 6.3.1
------ Adding platform: windows
You have been opted out of telemetry. To change this, run: cordova telemetry on.
No scripts found for hook "before_platform_add".
No version supplied. Retrieving version from config.xml...
Adding windows project...
PlatformApi successfully found for platform windows
Creating Cordova Windows Project:
 Path: platforms\windows
 Namespace: io.cordova.myapp669d3c
 Name: BlankCordovaApp4
Copying windows template project to c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows
Copying cordova-js sources to platform_www
Copying node_modules to c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows
Updating manifest files with project configuration.
Windows project created with cordova-windows@4.4.2
Checking for any plugins added to the project that have not been installed in windows platform
No differences found between plugins added to project and installed in windows platform. Continuing...
Merging project's config.xml into platform-specific windows config.xml
Found "merges/windows" folder. Copying its contents into the windows project.
Merging and updating files from [www, platforms\windows\platform_www, merges\windows] to platforms\windows\www
  mkdir platforms\windows\www\WinJS
  mkdir platforms\windows\www\WinJS\js
  copy  platforms\windows\platform_www\WinJS\js\base.js platforms\windows\www\WinJS\js\base.js (new file)
  mkdir platforms\windows\www\cordova-js-src
  copy  platforms\windows\platform_www\cordova-js-src\confighelper.js platforms\windows\www\cordova-js-src\confighelper.js (new file)
  copy  platforms\windows\platform_www\cordova-js-src\exec.js platforms\windows\www\cordova-js-src\exec.js (new file)
  copy  platforms\windows\platform_www\cordova-js-src\platform.js platforms\windows\www\cordova-js-src\platform.js (new file)
  copy  platforms\windows\platform_www\cordova-js-src\splashscreen.js platforms\windows\www\cordova-js-src\splashscreen.js (new file)
  copy  platforms\windows\platform_www\cordova.js platforms\windows\www\cordova.js (updated file)
  copy  www\css\index.css platforms\windows\www\css\index.css (updated file)
  copy  platforms\windows\platform_www\css\splashscreen.css platforms\windows\www\css\splashscreen.css (updated file)
  mkdir platforms\windows\www\images
  copy  www\images\cordova.png platforms\windows\www\images\cordova.png (new file)
  rmdir  platforms\windows\www\img (no source)
  delete platforms\windows\www\img\logo.png (no source)
  delete platforms\windows\www\img\smalllogo.png (no source)
  delete platforms\windows\www\img\splashscreen.png (no source)
  delete platforms\windows\www\img\storelogo.png (no source)
  copy  www\index.html platforms\windows\www\index.html (updated file)
  rmdir  platforms\windows\www\js (no source)
  delete platforms\windows\www\js\index.js (no source)
  mkdir platforms\windows\www\scripts
  copy  www\scripts\index.js platforms\windows\www\scripts\index.js (new file)
  copy  merges\windows\scripts\platformOverrides.js platforms\windows\www\scripts\platformOverrides.js (new file)
  copy  merges\windows\scripts\winstore-jscompat.js platforms\windows\www\scripts\winstore-jscompat.js (new file)
Updating icons and splash screens at platforms\windows\images
  copy  res/screens/windows/SplashScreen.scale-100.png platforms\windows\images\SplashScreen.scale-100.png (updated file)
  copy  res/screens/windows/SplashScreenPhone.scale-240.png platforms\windows\images\SplashScreenPhone.scale-240.png (updated file)
  copy  res/icons/windows/Square150x150Logo.scale-100.png platforms\windows\images\Square150x150Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square150x150Logo.scale-240.png platforms\windows\images\Square150x150Logo.scale-240.png (updated file)
  copy  res/icons/windows/Square30x30Logo.scale-100.png platforms\windows\images\Square30x30Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square310x310Logo.scale-100.png platforms\windows\images\Square310x310Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square44x44Logo.scale-100.png platforms\windows\images\Square44x44Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square44x44Logo.scale-240.png platforms\windows\images\Square44x44Logo.scale-240.png (updated file)
  copy  res/icons/windows/Square70x70Logo.scale-100.png platforms\windows\images\Square70x70Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square71x71Logo.scale-100.png platforms\windows\images\Square71x71Logo.scale-100.png (updated file)
  copy  res/icons/windows/Square71x71Logo.scale-240.png platforms\windows\images\Square71x71Logo.scale-240.png (updated file)
  copy  res/icons/windows/StoreLogo.scale-100.png platforms\windows\images\StoreLogo.scale-100.png (updated file)
  copy  res/icons/windows/StoreLogo.scale-240.png platforms\windows\images\StoreLogo.scale-240.png (updated file)
  copy  res/icons/windows/Wide310x150Logo.scale-100.png platforms\windows\images\Wide310x150Logo.scale-100.png (updated file)
  copy  res/icons/windows/Wide310x150Logo.scale-240.png platforms\windows\images\Wide310x150Logo.scale-240.png (updated file)
Prepared windows project successfully
No scripts found for hook "pre_package".
Installing plugin "com-intel-security-cordova-plugin" following successful platform add of windows
Found variables for "com-intel-security-cordova-plugin". Processing as cli_variables.
Installing "com-intel-security-cordova-plugin" for windows
Running command: cmd "/s /c ""c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\cordova\version.bat"""
Command finished with error code 0: cmd /s /c ""c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\cordova\version.bat""
Finding scripts for "before_plugin_install" hook from plugin com-intel-security-cordova-plugin on windows platform only.
No scripts found for hook "before_plugin_install".
Install start for "com-intel-security-cordova-plugin" on windows.
Beginning processing of action stack for windows project...
Action stack processing complete.
Install complete for com-intel-security-cordova-plugin on windows.
Finding scripts for "after_plugin_install" hook from plugin com-intel-security-cordova-plugin on windows platform only.
No scripts found for hook "after_plugin_install".
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml for saved platforms that haven't been added to the project
Checking for any plugins added to the project that have not been installed in windows platform
No differences found between plugins added to project and installed in windows platform. Continuing...
Generating platform-specific config.xml from defaults for windows at c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\config.xml
Merging project's config.xml into platform-specific windows config.xml
Found "merges/windows" folder. Copying its contents into the windows project.
Merging and updating files from [www, platforms\windows\platform_www, merges\windows] to platforms\windows\www
  copy  platforms\windows\platform_www\cordova-js-src\confighelper.js platforms\windows\www\cordova-js-src\confighelper.js (updated file)
  copy  platforms\windows\platform_www\cordova-js-src\exec.js platforms\windows\www\cordova-js-src\exec.js (updated file)
  copy  platforms\windows\platform_www\cordova-js-src\platform.js platforms\windows\www\cordova-js-src\platform.js (updated file)
  copy  platforms\windows\platform_www\cordova-js-src\splashscreen.js platforms\windows\www\cordova-js-src\splashscreen.js (updated file)
  copy  platforms\windows\platform_www\cordova_plugins.js platforms\windows\www\cordova_plugins.js (updated file)
  copy  www\css\index.css platforms\windows\www\css\index.css (updated file)
  copy  www\index.html platforms\windows\www\index.html (updated file)
  copy  platforms\windows\platform_www\plugins\com-intel-security-cordova-plugin\src\windows\servicesProxy.js platforms\windows\www\plugins\com-intel-security-cordova-plugin\src\windows\servicesProxy.js (updated file)
  copy  platforms\windows\platform_www\plugins\com-intel-security-cordova-plugin\www\appSecurityApi.js platforms\windows\www\plugins\com-intel-security-cordova-plugin\www\appSecurityApi.js (updated file)
  copy  platforms\windows\platform_www\plugins\com-intel-security-cordova-plugin\www\q-1\q.js platforms\windows\www\plugins\com-intel-security-cordova-plugin\www\q-1\q.js (updated file)
Updating icons and splash screens at platforms\windows\images
Prepared windows project successfully
No scripts found for hook "pre_package".
Executing script found in plugin com-intel-security-cordova-plugin for hook "after_prepare": plugins\com-intel-security-cordova-plugin\src\windows\ChooseArch_Windows.js
Checking config.xml for saved plugins that haven't been added to the project
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "cordova-plugin-whitelist@1.2.2"
Fetching plugin "cordova-plugin-whitelist@1.2.2" via npm
Fixed!
Copying plugin "C:\Users\mdTestAU\.cordova\lib\npm_cache\cordova-plugin-whitelist\1.2.2\package" => "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\plugins\cordova-plugin-whitelist"
Calling plugman.install on plugin "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\plugins\cordova-plugin-whitelist" for platform "windows
Installing "cordova-plugin-whitelist" for windows
Running command: cmd "/s /c ""c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\cordova\version.bat"""
Command finished with error code 0: cmd /s /c ""c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\cordova\version.bat""
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-whitelist on windows platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-whitelist" on windows.
Beginning processing of action stack for windows project...
Action stack processing complete.
Install complete for cordova-plugin-whitelist on windows.
Finding scripts for "after_plugin_install" hook from plugin cordova-plugin-whitelist on windows platform only.
No scripts found for hook "after_plugin_install".
No scripts found for hook "after_plugin_add".
Saving windows@4.4.2 into platforms.json
No scripts found for hook "after_platform_add".
------ Copying native files from c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\res\native\windows to c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows
------ Done copying native files to c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows
------ Building platform: windows
------ Build configuration options:  --debug -- --win --archs x86
You have been opted out of telemetry. To change this, run: cordova telemetry on.
No scripts found for hook "before_compile".
Reading build config file: c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\build.json
Running command: "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\msbuild.exe" -version -nologo
Command finished with error code 0: C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\msbuild.exe -version,-nologo
Building project: c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj
 Configuration : debug
 Platform      : x86
Running command: C:\Windows\system32\reg.exe query "HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows" /s /v InstallationFolder /reg:32
Command finished with error code 0: C:\Windows\system32\reg.exe query,HKLM\SOFTWARE\Microsoft\Microsoft SDKs\Windows,/s,/v,InstallationFolder,/reg:32
Running command: "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\msbuild.exe" "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj" /clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal /nologo /p:Configuration=debug /p:Platform=x86
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Microsoft.NetNative.ImportBefore.targets(25,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24208\Microsoft.NetNative.Settings.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Microsoft.NetNative.ImportBefore.targets (25,3)". This is most likely a build authoring error. This subsequent import will be ignored. [c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.Net.CoreRuntime.ImportAfter.targets(17,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0\.Net\CoreRuntime\Microsoft.Net.CoreRuntime.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.Net.CoreRuntime.ImportAfter.targets (17,3)". This is most likely a build authoring error. This subsequent import will be ignored. [c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NetNative.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0\.Net\.NetNative\15.0.24208\Microsoft.NetNative.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NetNative.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2140,5): warning MSB3842: Project "CordovaApp.Windows10" depends upon SDK "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" which supports apps targeting "UAP 10.0". To verify whether "Visual C++ 2015 Runtime for Universal Windows Platform Apps v14.0" is compatible with "UAP 10.0.14393.0", contact the SDK author or see http://go.microsoft.com/fwlink/?LinkID=309181. [c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj]
C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Microsoft.Cpp.VCLibs120Universal.targets(103,5): warning MSB3842: Project "CordovaApp.Windows10" depends upon SDK "Microsoft Universal CRT Debug Runtime v10.0.14393.0" which supports apps targeting "UAP 10.0". To verify whether "Microsoft Universal CRT Debug Runtime v10.0.14393.0" is compatible with "UAP 10.0.14393.0", contact the SDK author or see http://go.microsoft.com/fwlink/?LinkID=309181. [c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj]
  CordovaApp.Windows10 -> c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\CordovaApp.Windows10_1.0.0.0_x86_debug.appx
  Could not use a link to copy "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\.\AppX\Debug\ARM\Microsoft.VCLibs.ARM.Debug.14.00.appx" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Dependencies\ARM\Microsoft.VCLibs.ARM.Debug.14.00.appx". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\.\AppX\Debug\x64\Microsoft.VCLibs.x64.Debug.14.00.appx" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Dependencies\x64\Microsoft.VCLibs.x64.Debug.14.00.appx". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\.\AppX\Debug\x86\Microsoft.VCLibs.x86.Debug.14.00.appx" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Dependencies\x86\Microsoft.VCLibs.x86.Debug.14.00.appx". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.ps1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.ps1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\cs-CZ\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\cs-CZ\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\de-DE\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\de-DE\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\en-US\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\en-US\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\es-ES\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\es-ES\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\fr-FR\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\fr-FR\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\it-IT\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\it-IT\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\ja-JP\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\ja-JP\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\ko-KR\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\ko-KR\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\pl-PL\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\pl-PL\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\pt-BR\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\pt-BR\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\ru-RU\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\ru-RU\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\tr-TR\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\tr-TR\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\zh-CN\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\zh-CN\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Could not use a link to copy "C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Add-AppDevPackage.resources\zh-TW\Add-AppDevPackage.psd1" to "c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\Add-AppDevPackage.resources\zh-TW\Add-AppDevPackage.psd1". Copying the file instead. Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Command finished with error code 0: C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\msbuild.exe c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=x86
 BUILD OUTPUT: c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\platforms\windows\AppPackages\CordovaApp.Windows10_1.0.0.0_x86_debug_Test\CordovaApp.Windows10_1.0.0.0_x86_debug.appx
No scripts found for hook "after_build".
No scripts found for hook "after_compile".
------ Copying back to project: windows
------ Copying generated _pkginfo.txt file
------ Done copying compiled files: windows
------ Checking for: c:\users\mdtestau\documents\visual studio 2017\Projects\BlankCordovaApp4\BlankCordovaApp4\bin\Windows-x86\Debug\CordovaApp.Windows10.build.appxrecipe
------ Copying appx packages to output location
------ No packageOutputPath is specified for the project. Nothing to copy.
2>------ Deploy started: Project: BlankCordovaApp4, Configuration: Debug Windows-x86 ------
2>Could not locate the appxrecipe file. You may need to build your project.
2>Deployment failed.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by DanShmulIntel** [comment]
Thanks for the data about the issue. 
We have fixed it and published plugin v2.0.3.
