### ISSUE TITLE
secureStorage in browser or elsewhere on device

### ISSUE THREAD

**Issue by seanareed** [AppSecurityApi/com-intel-security-cordova-plugin#8]
I didn't see this in the docs anywhere.

Where is the secureStorage actually stored?

Is it within the browser (local storage for example) or elsewhere on the actual device?

Thanks

**Comment by DennisFilimonovIntel** [comment]
hi seanareed

Secure Storage items are stored on the device within the application sandbox, the items are encrypted and signed providing confidentiality and integrity.

**Comment by seanareed** [comment]
That's great, thanks!
